# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pyka.v1 import broker_pb2 as pyka_dot_v1_dot_broker__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pyka/v1/broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Metadata = channel.unary_unary(
                '/pyka.v1.Broker/Metadata',
                request_serializer=pyka_dot_v1_dot_broker__pb2.MetadataRequest.SerializeToString,
                response_deserializer=pyka_dot_v1_dot_broker__pb2.MetadataResponse.FromString,
                _registered_method=True)
        self.Produce = channel.unary_unary(
                '/pyka.v1.Broker/Produce',
                request_serializer=pyka_dot_v1_dot_broker__pb2.ProduceRequest.SerializeToString,
                response_deserializer=pyka_dot_v1_dot_broker__pb2.ProduceResponse.FromString,
                _registered_method=True)
        self.ProduceStream = channel.stream_stream(
                '/pyka.v1.Broker/ProduceStream',
                request_serializer=pyka_dot_v1_dot_broker__pb2.ProduceRequest.SerializeToString,
                response_deserializer=pyka_dot_v1_dot_broker__pb2.ProduceResponse.FromString,
                _registered_method=True)
        self.Consume = channel.unary_stream(
                '/pyka.v1.Broker/Consume',
                request_serializer=pyka_dot_v1_dot_broker__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=pyka_dot_v1_dot_broker__pb2.Record.FromString,
                _registered_method=True)


class BrokerServicer:
    """Missing associated documentation comment in .proto file."""

    def Metadata(self, request, context):
        """Where to send records for a topic. The routing table comes from the Ring;
        every broker returns the identical answer, so a client may ask any of them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Produce(self, request, context):
        """One record, one round trip. Simple and slow; use ProduceStream for volume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProduceStream(self, request_iterator, context):
        """Bidirectional: responses may arrive out of order relative to requests,
        which is what lets a client keep many appends in flight at once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Records from an offset onward. With follow=true the stream never ends and
        new records arrive as they are appended — B4's live tail is this flag,
        not a separate RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.Metadata,
                    request_deserializer=pyka_dot_v1_dot_broker__pb2.MetadataRequest.FromString,
                    response_serializer=pyka_dot_v1_dot_broker__pb2.MetadataResponse.SerializeToString,
            ),
            'Produce': grpc.unary_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=pyka_dot_v1_dot_broker__pb2.ProduceRequest.FromString,
                    response_serializer=pyka_dot_v1_dot_broker__pb2.ProduceResponse.SerializeToString,
            ),
            'ProduceStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProduceStream,
                    request_deserializer=pyka_dot_v1_dot_broker__pb2.ProduceRequest.FromString,
                    response_serializer=pyka_dot_v1_dot_broker__pb2.ProduceResponse.SerializeToString,
            ),
            'Consume': grpc.unary_stream_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=pyka_dot_v1_dot_broker__pb2.ConsumeRequest.FromString,
                    response_serializer=pyka_dot_v1_dot_broker__pb2.Record.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyka.v1.Broker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pyka.v1.Broker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Broker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyka.v1.Broker/Metadata',
            pyka_dot_v1_dot_broker__pb2.MetadataRequest.SerializeToString,
            pyka_dot_v1_dot_broker__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyka.v1.Broker/Produce',
            pyka_dot_v1_dot_broker__pb2.ProduceRequest.SerializeToString,
            pyka_dot_v1_dot_broker__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProduceStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pyka.v1.Broker/ProduceStream',
            pyka_dot_v1_dot_broker__pb2.ProduceRequest.SerializeToString,
            pyka_dot_v1_dot_broker__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pyka.v1.Broker/Consume',
            pyka_dot_v1_dot_broker__pb2.ConsumeRequest.SerializeToString,
            pyka_dot_v1_dot_broker__pb2.Record.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
